/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AcceptingGiftsMatch {
  'completionStatus' : boolean,
  'base' : BaseMatchEntry,
  'score' : bigint,
  'rulesReference' : string,
}
export interface ApiMatch {
  'makes' : [] | [bigint],
  'completionTime' : [] | [bigint],
  'completionStatus' : [] | [boolean],
  'owner' : Principal,
  'mode' : MatchMode,
  'attempts' : [] | [bigint],
  'score' : [] | [bigint],
  'rulesReference' : [] | [string],
  'matchId' : string,
  'players' : Array<Player>,
  'notes' : [] | [string],
  'dateTime' : Time,
  'streaks' : [] | [bigint],
}
export interface BaseMatchEntry {
  'owner' : Principal,
  'mode' : MatchMode,
  'matchId' : string,
  'players' : Array<Player>,
  'notes' : [] | [string],
  'dateTime' : Time,
}
export type MatchMode = { 'straightShot' : null } |
  { 'apaPractice' : null } |
  { 'acceptingGifts' : null };
export type MatchRecord = { 'straightShot' : StraightShotMatch } |
  { 'acceptingGifts' : AcceptingGiftsMatch } |
  { 'practice' : PracticeMatch };
export interface Player {
  'id' : Principal,
  'name' : string,
  'skillLevel' : [] | [bigint],
}
export interface PracticeMatch {
  'makes' : [] | [bigint],
  'base' : BaseMatchEntry,
  'attempts' : [] | [bigint],
  'streaks' : [] | [bigint],
}
export interface StraightShotMatch {
  'makes' : bigint,
  'completionTime' : [] | [bigint],
  'base' : BaseMatchEntry,
  'attempts' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearHistory' : ActorMethod<[], undefined>,
  'deleteMatch' : ActorMethod<[string], undefined>,
  'getAllMatches' : ActorMethod<[], Array<ApiMatch>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatch' : ActorMethod<[string], [] | [ApiMatch]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveMatch' : ActorMethod<[string, MatchRecord], undefined>,
  'updateMatch' : ActorMethod<[string, MatchRecord], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];