/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MatchMode = IDL.Variant({
  'straightShot' : IDL.Null,
  'apaPractice' : IDL.Null,
  'acceptingGifts' : IDL.Null,
});
export const Player = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'skillLevel' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const ApiMatch = IDL.Record({
  'makes' : IDL.Opt(IDL.Nat),
  'completionTime' : IDL.Opt(IDL.Nat),
  'completionStatus' : IDL.Opt(IDL.Bool),
  'owner' : IDL.Principal,
  'mode' : MatchMode,
  'attempts' : IDL.Opt(IDL.Nat),
  'score' : IDL.Opt(IDL.Nat),
  'rulesReference' : IDL.Opt(IDL.Text),
  'matchId' : IDL.Text,
  'players' : IDL.Vec(Player),
  'notes' : IDL.Opt(IDL.Text),
  'dateTime' : Time,
  'streaks' : IDL.Opt(IDL.Nat),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const BaseMatchEntry = IDL.Record({
  'owner' : IDL.Principal,
  'mode' : MatchMode,
  'matchId' : IDL.Text,
  'players' : IDL.Vec(Player),
  'notes' : IDL.Opt(IDL.Text),
  'dateTime' : Time,
});
export const StraightShotMatch = IDL.Record({
  'makes' : IDL.Nat,
  'completionTime' : IDL.Opt(IDL.Nat),
  'base' : BaseMatchEntry,
  'attempts' : IDL.Nat,
});
export const AcceptingGiftsMatch = IDL.Record({
  'completionStatus' : IDL.Bool,
  'base' : BaseMatchEntry,
  'score' : IDL.Nat,
  'rulesReference' : IDL.Text,
});
export const PracticeMatch = IDL.Record({
  'makes' : IDL.Opt(IDL.Nat),
  'base' : BaseMatchEntry,
  'attempts' : IDL.Opt(IDL.Nat),
  'streaks' : IDL.Opt(IDL.Nat),
});
export const MatchRecord = IDL.Variant({
  'straightShot' : StraightShotMatch,
  'acceptingGifts' : AcceptingGiftsMatch,
  'practice' : PracticeMatch,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearHistory' : IDL.Func([], [], []),
  'deleteMatch' : IDL.Func([IDL.Text], [], []),
  'getAllMatches' : IDL.Func([], [IDL.Vec(ApiMatch)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatch' : IDL.Func([IDL.Text], [IDL.Opt(ApiMatch)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveMatch' : IDL.Func([IDL.Text, MatchRecord], [], []),
  'updateMatch' : IDL.Func([IDL.Text, MatchRecord], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MatchMode = IDL.Variant({
    'straightShot' : IDL.Null,
    'apaPractice' : IDL.Null,
    'acceptingGifts' : IDL.Null,
  });
  const Player = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'skillLevel' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const ApiMatch = IDL.Record({
    'makes' : IDL.Opt(IDL.Nat),
    'completionTime' : IDL.Opt(IDL.Nat),
    'completionStatus' : IDL.Opt(IDL.Bool),
    'owner' : IDL.Principal,
    'mode' : MatchMode,
    'attempts' : IDL.Opt(IDL.Nat),
    'score' : IDL.Opt(IDL.Nat),
    'rulesReference' : IDL.Opt(IDL.Text),
    'matchId' : IDL.Text,
    'players' : IDL.Vec(Player),
    'notes' : IDL.Opt(IDL.Text),
    'dateTime' : Time,
    'streaks' : IDL.Opt(IDL.Nat),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const BaseMatchEntry = IDL.Record({
    'owner' : IDL.Principal,
    'mode' : MatchMode,
    'matchId' : IDL.Text,
    'players' : IDL.Vec(Player),
    'notes' : IDL.Opt(IDL.Text),
    'dateTime' : Time,
  });
  const StraightShotMatch = IDL.Record({
    'makes' : IDL.Nat,
    'completionTime' : IDL.Opt(IDL.Nat),
    'base' : BaseMatchEntry,
    'attempts' : IDL.Nat,
  });
  const AcceptingGiftsMatch = IDL.Record({
    'completionStatus' : IDL.Bool,
    'base' : BaseMatchEntry,
    'score' : IDL.Nat,
    'rulesReference' : IDL.Text,
  });
  const PracticeMatch = IDL.Record({
    'makes' : IDL.Opt(IDL.Nat),
    'base' : BaseMatchEntry,
    'attempts' : IDL.Opt(IDL.Nat),
    'streaks' : IDL.Opt(IDL.Nat),
  });
  const MatchRecord = IDL.Variant({
    'straightShot' : StraightShotMatch,
    'acceptingGifts' : AcceptingGiftsMatch,
    'practice' : PracticeMatch,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearHistory' : IDL.Func([], [], []),
    'deleteMatch' : IDL.Func([IDL.Text], [], []),
    'getAllMatches' : IDL.Func([], [IDL.Vec(ApiMatch)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatch' : IDL.Func([IDL.Text], [IDL.Opt(ApiMatch)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveMatch' : IDL.Func([IDL.Text, MatchRecord], [], []),
    'updateMatch' : IDL.Func([IDL.Text, MatchRecord], [], []),
  });
};

export const init = ({ IDL }) => { return []; };