/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface APA9MatchPlayerStatsUi {
  'id' : string,
  'ppi' : number,
  'rankIcon' : string,
  'matchType' : string,
  'breakMaidenCount' : bigint,
  'defensiveShots' : bigint,
  'pointsAwarded' : bigint,
  'matchBehaviorPhase' : string,
  'totalBallsScoredPerRack' : Array<bigint>,
  'breakRuns' : Array<bigint>,
  'runOutAttempts' : bigint,
  'inningScores' : Array<bigint>,
  'rank' : string,
  'rackCount' : bigint,
  'pointsNeeded' : bigint,
  'deadBallsPerRack' : Array<bigint>,
  'pointsWonConverted' : bigint,
  'level' : { 'all' : null } |
    { 'playerMatch' : null } |
    { 'teamMatch' : null } |
    { 'detailRack' : null },
  'totalScore' : bigint,
  'summary' : string,
  'rackStats' : APAMatchStatsUiRackStats,
  'innings' : bigint,
  'timestamp' : Time,
  'validBreakCount' : bigint,
  'ballsOnBreakAwardedToOpponentCount' : bigint,
  'winPercentage' : number,
  'pointsEarnedRunningTotal' : bigint,
  'isPlayerOfMatch' : boolean,
  'comments' : string,
  'skillLevel' : bigint,
  'runOutCount' : bigint,
  'umpire' : string,
  'racksPlayed' : bigint,
  'seasonType' : string,
  'location' : string,
  'ballsOnBreak' : Array<bigint>,
  'points' : bigint,
}
export interface APADetailedInnningSummary {
  'defensiveShots' : bigint,
  'player' : string,
  'deadBalls' : bigint,
  'points' : bigint,
}
export interface APAMatchStatsUiContainer {
  'matchType' : string,
  'summary' : APAMatchStatsUiSummary,
  'players' : Array<[] | [APA9MatchPlayerStatsUi]>,
  'seasonType' : string,
}
export interface APAMatchStatsUiRackStats {
  'extraStats' : string,
  'description' : string,
  'summary' : string,
  'matchId' : string,
  'playerStats' : Array<[] | [APA9MatchPlayerStatsUi]>,
  'rackStats' : Array<RackStat>,
  'timestamp' : Time,
  'rackNumber' : bigint,
}
export interface APAMatchStatsUiSummary {
  'id' : string,
  'matchType' : string,
  'extraStats' : string,
  'pointsAwarded' : bigint,
  'level' : { 'all' : null } |
    { 'playerMatch' : null } |
    { 'teamMatch' : null } |
    { 'detailRack' : null },
  'summary' : string,
  'playerStats' : Array<[] | [APA9MatchPlayerStatsUi]>,
  'rackStats' : APAMatchStatsUiRackStats,
  'timestamp' : Time,
  'isInProgress' : boolean,
  'comments' : string,
  'phase' : string,
  'umpire' : [] | [Principal],
  'seasonType' : string,
  'location' : string,
  'points' : bigint,
}
export interface AcceptingGiftsMatch {
  'completionStatus' : boolean,
  'base' : BaseMatchEntry,
  'score' : bigint,
  'rulesReference' : string,
}
export interface ApaNineBallMatch {
  'matchType' : string,
  'base' : BaseMatchEntry,
  'winner' : Principal,
  'playerStats' : Array<ApaPlayerStats>,
  'teamStats' : Array<TeamStats>,
  'umpire' : [] | [Principal],
  'seasonType' : string,
}
export interface ApaPlayerStats {
  'ppi' : number,
  'defensiveShots' : bigint,
  'matchBehaviorPhase' : string,
  'playerId' : Principal,
  'pointsNeeded' : bigint,
  'pointsWonConverted' : bigint,
  'totalScore' : bigint,
  'innings' : bigint,
  'winPercentage' : number,
  'pointsEarnedRunningTotal' : bigint,
  'isPlayerOfMatch' : boolean,
  'skillLevel' : bigint,
  'racks' : Array<RackScore>,
}
export interface ApiMatch {
  'makes' : [] | [bigint],
  'thirdShotScore' : [] | [bigint],
  'completionTime' : [] | [bigint],
  'completionStatus' : [] | [boolean],
  'owner' : Principal,
  'scratchStrokes' : [] | [Array<bigint>],
  'mode' : MatchMode,
  'attempts' : [] | [bigint],
  'score' : [] | [bigint],
  'shots' : [] | [bigint],
  'totalScore' : [] | [bigint],
  'rulesReference' : [] | [string],
  'fourthShotScore' : [] | [bigint],
  'matchId' : string,
  'players' : Array<Player>,
  'firstShotScore' : [] | [bigint],
  'ballsMade' : [] | [bigint],
  'notes' : [] | [string],
  'apaMatchInfo' : [] | [APAMatchStatsUiContainer],
  'secondShotScore' : [] | [bigint],
  'dateTime' : Time,
  'streaks' : [] | [bigint],
  'strokes' : [] | [Array<bigint>],
}
export interface BallState {
  'by' : string,
  'id' : bigint,
  'all' : string,
  'eoi' : boolean,
  'inn' : bigint,
  'pna' : bigint,
  'ballNumber' : bigint,
  'calledShot' : boolean,
  'runOut' : string,
  'difficulty' : string,
  'rack' : bigint,
  'gameId' : string,
  'isBreak' : boolean,
  'defensiveShot' : boolean,
  'positionPlay' : string,
  'intendedPocket' : string,
  'score' : bigint,
  'pocketed' : string,
  'finalBall' : bigint,
  'activePlayer' : string,
  'defense' : boolean,
  'points' : bigint,
}
export interface BaseMatchEntry {
  'owner' : Principal,
  'mode' : MatchMode,
  'matchId' : string,
  'players' : Array<Player>,
  'notes' : [] | [string],
  'dateTime' : Time,
}
export type MatchMode = { 'straightShot' : null } |
  { 'apaPractice' : null } |
  { 'acceptingGifts' : null };
export type MatchRecord = { 'straightShot' : StraightShotMatch } |
  { 'acceptingGifts' : AcceptingGiftsMatch } |
  { 'practice' : PracticeMatch } |
  { 'apaNineBall' : ApaNineBallMatch };
export interface Player {
  'id' : Principal,
  'name' : string,
  'skillLevel' : [] | [bigint],
}
export interface PracticeMatch {
  'makes' : [] | [bigint],
  'base' : BaseMatchEntry,
  'attempts' : [] | [bigint],
  'streaks' : [] | [bigint],
}
export interface RackScore {
  'validBreak' : boolean,
  'breakMaiden' : boolean,
  'runOut' : boolean,
  'totalRackScore' : bigint,
  'ballsOnBreakAwardedToOpponent' : bigint,
  'inningScore' : bigint,
  'ballsOnBreak' : bigint,
  'deadBalls' : bigint,
}
export interface RackStat {
  'extraStats' : string,
  'description' : string,
  'summary' : string,
  'matchId' : string,
  'timestamp' : Time,
  'rackNumberCopy' : bigint,
  'rackNumber' : bigint,
}
export interface StraightShotMatch {
  'base' : BaseMatchEntry,
  'scratchStrokes' : Array<bigint>,
  'time' : [] | [bigint],
  'score' : {
    'firstShot' : bigint,
    'total' : bigint,
    'fourthShot' : bigint,
    'thirdShot' : bigint,
    'secondShot' : bigint,
  },
  'shots' : bigint,
  'ballsMade' : bigint,
  'strokes' : Array<bigint>,
}
export interface TeamStats {
  'teamName' : string,
  'teamAverageScore' : number,
  'score' : { 'totalPoints' : bigint },
  'playtimes' : Array<number>,
  'matchesPlayed' : bigint,
  'teamId' : string,
  'matchesWon' : bigint,
  'teamWinState' : { 'win' : string } |
    { 'loss' : string } |
    { 'teammatchInProgress' : null } |
    { 'forfeit' : string },
  'teamPenaltyState' : { 'penalty' : string } |
    { 'pending' : null } |
    { 'none' : null } |
    { 'penaltyAwarded' : string },
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearHistory' : ActorMethod<[], undefined>,
  'computeAPASummary' : ActorMethod<
    [string, Array<BallState>],
    APADetailedInnningSummary
  >,
  'deleteMatch' : ActorMethod<[string], undefined>,
  'getAllMatches' : ActorMethod<[], Array<ApiMatch>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatch' : ActorMethod<[string], [] | [ApiMatch]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveMatch' : ActorMethod<[string, MatchRecord], undefined>,
  'updateMatch' : ActorMethod<[string, MatchRecord], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];