/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const APA9MatchPlayerStatsUi = IDL.Rec();
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BallState = IDL.Record({
  'by' : IDL.Text,
  'id' : IDL.Int,
  'all' : IDL.Text,
  'eoi' : IDL.Bool,
  'inn' : IDL.Int,
  'pna' : IDL.Int,
  'ballNumber' : IDL.Int,
  'calledShot' : IDL.Bool,
  'runOut' : IDL.Text,
  'difficulty' : IDL.Text,
  'rack' : IDL.Int,
  'gameId' : IDL.Text,
  'isBreak' : IDL.Bool,
  'defensiveShot' : IDL.Bool,
  'positionPlay' : IDL.Text,
  'intendedPocket' : IDL.Text,
  'score' : IDL.Int,
  'pocketed' : IDL.Text,
  'finalBall' : IDL.Int,
  'activePlayer' : IDL.Text,
  'defense' : IDL.Bool,
  'points' : IDL.Int,
});
export const APADetailedInnningSummary = IDL.Record({
  'defensiveShots' : IDL.Nat,
  'player' : IDL.Text,
  'deadBalls' : IDL.Nat,
  'points' : IDL.Nat,
});
export const MatchMode = IDL.Variant({
  'straightShot' : IDL.Null,
  'apaPractice' : IDL.Null,
  'acceptingGifts' : IDL.Null,
});
export const Player = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'skillLevel' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const RackStat = IDL.Record({
  'extraStats' : IDL.Text,
  'description' : IDL.Text,
  'summary' : IDL.Text,
  'matchId' : IDL.Text,
  'timestamp' : Time,
  'rackNumberCopy' : IDL.Nat,
  'rackNumber' : IDL.Nat,
});
export const APAMatchStatsUiRackStats = IDL.Record({
  'extraStats' : IDL.Text,
  'description' : IDL.Text,
  'summary' : IDL.Text,
  'matchId' : IDL.Text,
  'playerStats' : IDL.Vec(IDL.Opt(APA9MatchPlayerStatsUi)),
  'rackStats' : IDL.Vec(RackStat),
  'timestamp' : Time,
  'rackNumber' : IDL.Nat,
});
APA9MatchPlayerStatsUi.fill(
  IDL.Record({
    'id' : IDL.Text,
    'ppi' : IDL.Float64,
    'rankIcon' : IDL.Text,
    'matchType' : IDL.Text,
    'breakMaidenCount' : IDL.Nat,
    'defensiveShots' : IDL.Nat,
    'pointsAwarded' : IDL.Nat,
    'matchBehaviorPhase' : IDL.Text,
    'totalBallsScoredPerRack' : IDL.Vec(IDL.Nat),
    'breakRuns' : IDL.Vec(IDL.Nat),
    'runOutAttempts' : IDL.Nat,
    'inningScores' : IDL.Vec(IDL.Int),
    'rank' : IDL.Text,
    'rackCount' : IDL.Nat,
    'pointsNeeded' : IDL.Nat,
    'deadBallsPerRack' : IDL.Vec(IDL.Nat),
    'pointsWonConverted' : IDL.Nat,
    'level' : IDL.Variant({
      'all' : IDL.Null,
      'playerMatch' : IDL.Null,
      'teamMatch' : IDL.Null,
      'detailRack' : IDL.Null,
    }),
    'totalScore' : IDL.Int,
    'summary' : IDL.Text,
    'rackStats' : APAMatchStatsUiRackStats,
    'innings' : IDL.Nat,
    'timestamp' : Time,
    'validBreakCount' : IDL.Nat,
    'ballsOnBreakAwardedToOpponentCount' : IDL.Nat,
    'winPercentage' : IDL.Float64,
    'pointsEarnedRunningTotal' : IDL.Nat,
    'isPlayerOfMatch' : IDL.Bool,
    'comments' : IDL.Text,
    'skillLevel' : IDL.Nat,
    'runOutCount' : IDL.Nat,
    'umpire' : IDL.Text,
    'racksPlayed' : IDL.Nat,
    'seasonType' : IDL.Text,
    'location' : IDL.Text,
    'ballsOnBreak' : IDL.Vec(IDL.Int),
    'points' : IDL.Nat,
  })
);
export const APAMatchStatsUiSummary = IDL.Record({
  'id' : IDL.Text,
  'matchType' : IDL.Text,
  'extraStats' : IDL.Text,
  'pointsAwarded' : IDL.Nat,
  'level' : IDL.Variant({
    'all' : IDL.Null,
    'playerMatch' : IDL.Null,
    'teamMatch' : IDL.Null,
    'detailRack' : IDL.Null,
  }),
  'summary' : IDL.Text,
  'playerStats' : IDL.Vec(IDL.Opt(APA9MatchPlayerStatsUi)),
  'rackStats' : APAMatchStatsUiRackStats,
  'timestamp' : Time,
  'isInProgress' : IDL.Bool,
  'comments' : IDL.Text,
  'phase' : IDL.Text,
  'umpire' : IDL.Opt(IDL.Principal),
  'seasonType' : IDL.Text,
  'location' : IDL.Text,
  'points' : IDL.Nat,
});
export const APAMatchStatsUiContainer = IDL.Record({
  'matchType' : IDL.Text,
  'summary' : APAMatchStatsUiSummary,
  'players' : IDL.Vec(IDL.Opt(APA9MatchPlayerStatsUi)),
  'seasonType' : IDL.Text,
});
export const ApiMatch = IDL.Record({
  'makes' : IDL.Opt(IDL.Nat),
  'thirdShotScore' : IDL.Opt(IDL.Nat),
  'startingObjectBallCount' : IDL.Opt(IDL.Nat),
  'completionTime' : IDL.Opt(IDL.Nat),
  'completionStatus' : IDL.Opt(IDL.Bool),
  'owner' : IDL.Principal,
  'scratchStrokes' : IDL.Opt(IDL.Vec(IDL.Nat)),
  'mode' : MatchMode,
  'attempts' : IDL.Opt(IDL.Nat),
  'endingObjectBallCount' : IDL.Opt(IDL.Nat),
  'score' : IDL.Opt(IDL.Nat),
  'shots' : IDL.Opt(IDL.Nat),
  'finalSetScorePlayer' : IDL.Opt(IDL.Nat),
  'totalScore' : IDL.Opt(IDL.Nat),
  'rulesReference' : IDL.Opt(IDL.Text),
  'fourthShotScore' : IDL.Opt(IDL.Nat),
  'matchId' : IDL.Text,
  'players' : IDL.Vec(Player),
  'totalAttempts' : IDL.Opt(IDL.Nat),
  'firstShotScore' : IDL.Opt(IDL.Nat),
  'ballsMade' : IDL.Opt(IDL.Nat),
  'notes' : IDL.Opt(IDL.Text),
  'apaMatchInfo' : IDL.Opt(APAMatchStatsUiContainer),
  'secondShotScore' : IDL.Opt(IDL.Nat),
  'dateTime' : Time,
  'officialApaMatchLogData' : IDL.Opt(
    IDL.Record({
      'defensiveShots' : IDL.Text,
      'theirScore' : IDL.Text,
      'myScore' : IDL.Text,
      'date' : IDL.Text,
      'opponentName' : IDL.Text,
      'notes' : IDL.Text,
      'innings' : IDL.Text,
      'points' : IDL.Text,
    })
  ),
  'finalSetScoreGhost' : IDL.Opt(IDL.Nat),
  'streaks' : IDL.Opt(IDL.Nat),
  'strokes' : IDL.Opt(IDL.Vec(IDL.Nat)),
  'setsCompleted' : IDL.Opt(IDL.Nat),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'apaSkillLevel' : IDL.Opt(IDL.Nat),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const BaseMatchEntry = IDL.Record({
  'owner' : IDL.Principal,
  'mode' : MatchMode,
  'matchId' : IDL.Text,
  'players' : IDL.Vec(Player),
  'notes' : IDL.Opt(IDL.Text),
  'dateTime' : Time,
});
export const StraightShotMatch = IDL.Record({
  'base' : BaseMatchEntry,
  'scratchStrokes' : IDL.Vec(IDL.Nat),
  'time' : IDL.Opt(IDL.Nat),
  'score' : IDL.Record({
    'firstShot' : IDL.Nat,
    'total' : IDL.Nat,
    'fourthShot' : IDL.Nat,
    'thirdShot' : IDL.Nat,
    'secondShot' : IDL.Nat,
  }),
  'shots' : IDL.Nat,
  'ballsMade' : IDL.Nat,
  'strokes' : IDL.Vec(IDL.Nat),
});
export const AcceptingGiftsMatch = IDL.Record({
  'startingObjectBallCount' : IDL.Nat,
  'completionStatus' : IDL.Bool,
  'base' : BaseMatchEntry,
  'endingObjectBallCount' : IDL.Nat,
  'score' : IDL.Nat,
  'finalSetScorePlayer' : IDL.Nat,
  'rulesReference' : IDL.Text,
  'totalAttempts' : IDL.Nat,
  'finalSetScoreGhost' : IDL.Nat,
  'setsCompleted' : IDL.Nat,
});
export const OfficialApaMatchLog = IDL.Record({
  'defensiveShots' : IDL.Text,
  'theirScore' : IDL.Text,
  'myScore' : IDL.Text,
  'owner' : IDL.Principal,
  'date' : IDL.Text,
  'opponentName' : IDL.Text,
  'matchId' : IDL.Text,
  'notes' : IDL.Text,
  'innings' : IDL.Text,
  'dateTime' : Time,
  'points' : IDL.Text,
});
export const PracticeMatch = IDL.Record({
  'makes' : IDL.Opt(IDL.Nat),
  'base' : BaseMatchEntry,
  'attempts' : IDL.Opt(IDL.Nat),
  'streaks' : IDL.Opt(IDL.Nat),
});
export const RackScore = IDL.Record({
  'validBreak' : IDL.Bool,
  'breakMaiden' : IDL.Bool,
  'runOut' : IDL.Bool,
  'totalRackScore' : IDL.Nat,
  'ballsOnBreakAwardedToOpponent' : IDL.Nat,
  'inningScore' : IDL.Int,
  'ballsOnBreak' : IDL.Int,
  'deadBalls' : IDL.Nat,
});
export const ApaPlayerStats = IDL.Record({
  'ppi' : IDL.Float64,
  'defensiveShots' : IDL.Nat,
  'matchBehaviorPhase' : IDL.Text,
  'playerId' : IDL.Principal,
  'pointsNeeded' : IDL.Nat,
  'pointsWonConverted' : IDL.Nat,
  'totalScore' : IDL.Int,
  'innings' : IDL.Nat,
  'winPercentage' : IDL.Float64,
  'pointsEarnedRunningTotal' : IDL.Nat,
  'isPlayerOfMatch' : IDL.Bool,
  'skillLevel' : IDL.Nat,
  'racks' : IDL.Vec(RackScore),
});
export const TeamStats = IDL.Record({
  'teamName' : IDL.Text,
  'teamAverageScore' : IDL.Float64,
  'score' : IDL.Record({ 'totalPoints' : IDL.Int }),
  'playtimes' : IDL.Vec(IDL.Float64),
  'matchesPlayed' : IDL.Nat,
  'teamId' : IDL.Text,
  'matchesWon' : IDL.Nat,
  'teamWinState' : IDL.Variant({
    'win' : IDL.Text,
    'loss' : IDL.Text,
    'teammatchInProgress' : IDL.Null,
    'forfeit' : IDL.Text,
  }),
  'teamPenaltyState' : IDL.Variant({
    'penalty' : IDL.Text,
    'pending' : IDL.Null,
    'none' : IDL.Null,
    'penaltyAwarded' : IDL.Text,
  }),
});
export const ApaNineBallMatch = IDL.Record({
  'matchType' : IDL.Text,
  'base' : BaseMatchEntry,
  'winner' : IDL.Principal,
  'playerStats' : IDL.Vec(ApaPlayerStats),
  'teamStats' : IDL.Vec(TeamStats),
  'umpire' : IDL.Opt(IDL.Principal),
  'seasonType' : IDL.Text,
});
export const MatchLogRecord = IDL.Variant({
  'straightShot' : StraightShotMatch,
  'acceptingGifts' : AcceptingGiftsMatch,
  'officialApaMatchLog' : OfficialApaMatchLog,
  'practice' : PracticeMatch,
  'apaNineBall' : ApaNineBallMatch,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearHistory' : IDL.Func([], [], []),
  'completeSession' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'computeAPASummary' : IDL.Func(
      [IDL.Text, IDL.Vec(BallState)],
      [APADetailedInnningSummary],
      [],
    ),
  'deleteMatch' : IDL.Func([IDL.Text], [], []),
  'getAllMatches' : IDL.Func([], [IDL.Vec(ApiMatch)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentObjectBallCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getInviteOnlyMode' : IDL.Func([], [IDL.Bool], ['query']),
  'getMatch' : IDL.Func([IDL.Text], [IDL.Opt(ApiMatch)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveMatch' : IDL.Func([IDL.Text, MatchLogRecord], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setCurrentObjectBallCount' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'setInviteOnlyMode' : IDL.Func([IDL.Bool], [], []),
  'updateMatch' : IDL.Func([IDL.Text, MatchLogRecord], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const APA9MatchPlayerStatsUi = IDL.Rec();
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BallState = IDL.Record({
    'by' : IDL.Text,
    'id' : IDL.Int,
    'all' : IDL.Text,
    'eoi' : IDL.Bool,
    'inn' : IDL.Int,
    'pna' : IDL.Int,
    'ballNumber' : IDL.Int,
    'calledShot' : IDL.Bool,
    'runOut' : IDL.Text,
    'difficulty' : IDL.Text,
    'rack' : IDL.Int,
    'gameId' : IDL.Text,
    'isBreak' : IDL.Bool,
    'defensiveShot' : IDL.Bool,
    'positionPlay' : IDL.Text,
    'intendedPocket' : IDL.Text,
    'score' : IDL.Int,
    'pocketed' : IDL.Text,
    'finalBall' : IDL.Int,
    'activePlayer' : IDL.Text,
    'defense' : IDL.Bool,
    'points' : IDL.Int,
  });
  const APADetailedInnningSummary = IDL.Record({
    'defensiveShots' : IDL.Nat,
    'player' : IDL.Text,
    'deadBalls' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const MatchMode = IDL.Variant({
    'straightShot' : IDL.Null,
    'apaPractice' : IDL.Null,
    'acceptingGifts' : IDL.Null,
  });
  const Player = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'skillLevel' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const RackStat = IDL.Record({
    'extraStats' : IDL.Text,
    'description' : IDL.Text,
    'summary' : IDL.Text,
    'matchId' : IDL.Text,
    'timestamp' : Time,
    'rackNumberCopy' : IDL.Nat,
    'rackNumber' : IDL.Nat,
  });
  const APAMatchStatsUiRackStats = IDL.Record({
    'extraStats' : IDL.Text,
    'description' : IDL.Text,
    'summary' : IDL.Text,
    'matchId' : IDL.Text,
    'playerStats' : IDL.Vec(IDL.Opt(APA9MatchPlayerStatsUi)),
    'rackStats' : IDL.Vec(RackStat),
    'timestamp' : Time,
    'rackNumber' : IDL.Nat,
  });
  APA9MatchPlayerStatsUi.fill(
    IDL.Record({
      'id' : IDL.Text,
      'ppi' : IDL.Float64,
      'rankIcon' : IDL.Text,
      'matchType' : IDL.Text,
      'breakMaidenCount' : IDL.Nat,
      'defensiveShots' : IDL.Nat,
      'pointsAwarded' : IDL.Nat,
      'matchBehaviorPhase' : IDL.Text,
      'totalBallsScoredPerRack' : IDL.Vec(IDL.Nat),
      'breakRuns' : IDL.Vec(IDL.Nat),
      'runOutAttempts' : IDL.Nat,
      'inningScores' : IDL.Vec(IDL.Int),
      'rank' : IDL.Text,
      'rackCount' : IDL.Nat,
      'pointsNeeded' : IDL.Nat,
      'deadBallsPerRack' : IDL.Vec(IDL.Nat),
      'pointsWonConverted' : IDL.Nat,
      'level' : IDL.Variant({
        'all' : IDL.Null,
        'playerMatch' : IDL.Null,
        'teamMatch' : IDL.Null,
        'detailRack' : IDL.Null,
      }),
      'totalScore' : IDL.Int,
      'summary' : IDL.Text,
      'rackStats' : APAMatchStatsUiRackStats,
      'innings' : IDL.Nat,
      'timestamp' : Time,
      'validBreakCount' : IDL.Nat,
      'ballsOnBreakAwardedToOpponentCount' : IDL.Nat,
      'winPercentage' : IDL.Float64,
      'pointsEarnedRunningTotal' : IDL.Nat,
      'isPlayerOfMatch' : IDL.Bool,
      'comments' : IDL.Text,
      'skillLevel' : IDL.Nat,
      'runOutCount' : IDL.Nat,
      'umpire' : IDL.Text,
      'racksPlayed' : IDL.Nat,
      'seasonType' : IDL.Text,
      'location' : IDL.Text,
      'ballsOnBreak' : IDL.Vec(IDL.Int),
      'points' : IDL.Nat,
    })
  );
  const APAMatchStatsUiSummary = IDL.Record({
    'id' : IDL.Text,
    'matchType' : IDL.Text,
    'extraStats' : IDL.Text,
    'pointsAwarded' : IDL.Nat,
    'level' : IDL.Variant({
      'all' : IDL.Null,
      'playerMatch' : IDL.Null,
      'teamMatch' : IDL.Null,
      'detailRack' : IDL.Null,
    }),
    'summary' : IDL.Text,
    'playerStats' : IDL.Vec(IDL.Opt(APA9MatchPlayerStatsUi)),
    'rackStats' : APAMatchStatsUiRackStats,
    'timestamp' : Time,
    'isInProgress' : IDL.Bool,
    'comments' : IDL.Text,
    'phase' : IDL.Text,
    'umpire' : IDL.Opt(IDL.Principal),
    'seasonType' : IDL.Text,
    'location' : IDL.Text,
    'points' : IDL.Nat,
  });
  const APAMatchStatsUiContainer = IDL.Record({
    'matchType' : IDL.Text,
    'summary' : APAMatchStatsUiSummary,
    'players' : IDL.Vec(IDL.Opt(APA9MatchPlayerStatsUi)),
    'seasonType' : IDL.Text,
  });
  const ApiMatch = IDL.Record({
    'makes' : IDL.Opt(IDL.Nat),
    'thirdShotScore' : IDL.Opt(IDL.Nat),
    'startingObjectBallCount' : IDL.Opt(IDL.Nat),
    'completionTime' : IDL.Opt(IDL.Nat),
    'completionStatus' : IDL.Opt(IDL.Bool),
    'owner' : IDL.Principal,
    'scratchStrokes' : IDL.Opt(IDL.Vec(IDL.Nat)),
    'mode' : MatchMode,
    'attempts' : IDL.Opt(IDL.Nat),
    'endingObjectBallCount' : IDL.Opt(IDL.Nat),
    'score' : IDL.Opt(IDL.Nat),
    'shots' : IDL.Opt(IDL.Nat),
    'finalSetScorePlayer' : IDL.Opt(IDL.Nat),
    'totalScore' : IDL.Opt(IDL.Nat),
    'rulesReference' : IDL.Opt(IDL.Text),
    'fourthShotScore' : IDL.Opt(IDL.Nat),
    'matchId' : IDL.Text,
    'players' : IDL.Vec(Player),
    'totalAttempts' : IDL.Opt(IDL.Nat),
    'firstShotScore' : IDL.Opt(IDL.Nat),
    'ballsMade' : IDL.Opt(IDL.Nat),
    'notes' : IDL.Opt(IDL.Text),
    'apaMatchInfo' : IDL.Opt(APAMatchStatsUiContainer),
    'secondShotScore' : IDL.Opt(IDL.Nat),
    'dateTime' : Time,
    'officialApaMatchLogData' : IDL.Opt(
      IDL.Record({
        'defensiveShots' : IDL.Text,
        'theirScore' : IDL.Text,
        'myScore' : IDL.Text,
        'date' : IDL.Text,
        'opponentName' : IDL.Text,
        'notes' : IDL.Text,
        'innings' : IDL.Text,
        'points' : IDL.Text,
      })
    ),
    'finalSetScoreGhost' : IDL.Opt(IDL.Nat),
    'streaks' : IDL.Opt(IDL.Nat),
    'strokes' : IDL.Opt(IDL.Vec(IDL.Nat)),
    'setsCompleted' : IDL.Opt(IDL.Nat),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'apaSkillLevel' : IDL.Opt(IDL.Nat),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const BaseMatchEntry = IDL.Record({
    'owner' : IDL.Principal,
    'mode' : MatchMode,
    'matchId' : IDL.Text,
    'players' : IDL.Vec(Player),
    'notes' : IDL.Opt(IDL.Text),
    'dateTime' : Time,
  });
  const StraightShotMatch = IDL.Record({
    'base' : BaseMatchEntry,
    'scratchStrokes' : IDL.Vec(IDL.Nat),
    'time' : IDL.Opt(IDL.Nat),
    'score' : IDL.Record({
      'firstShot' : IDL.Nat,
      'total' : IDL.Nat,
      'fourthShot' : IDL.Nat,
      'thirdShot' : IDL.Nat,
      'secondShot' : IDL.Nat,
    }),
    'shots' : IDL.Nat,
    'ballsMade' : IDL.Nat,
    'strokes' : IDL.Vec(IDL.Nat),
  });
  const AcceptingGiftsMatch = IDL.Record({
    'startingObjectBallCount' : IDL.Nat,
    'completionStatus' : IDL.Bool,
    'base' : BaseMatchEntry,
    'endingObjectBallCount' : IDL.Nat,
    'score' : IDL.Nat,
    'finalSetScorePlayer' : IDL.Nat,
    'rulesReference' : IDL.Text,
    'totalAttempts' : IDL.Nat,
    'finalSetScoreGhost' : IDL.Nat,
    'setsCompleted' : IDL.Nat,
  });
  const OfficialApaMatchLog = IDL.Record({
    'defensiveShots' : IDL.Text,
    'theirScore' : IDL.Text,
    'myScore' : IDL.Text,
    'owner' : IDL.Principal,
    'date' : IDL.Text,
    'opponentName' : IDL.Text,
    'matchId' : IDL.Text,
    'notes' : IDL.Text,
    'innings' : IDL.Text,
    'dateTime' : Time,
    'points' : IDL.Text,
  });
  const PracticeMatch = IDL.Record({
    'makes' : IDL.Opt(IDL.Nat),
    'base' : BaseMatchEntry,
    'attempts' : IDL.Opt(IDL.Nat),
    'streaks' : IDL.Opt(IDL.Nat),
  });
  const RackScore = IDL.Record({
    'validBreak' : IDL.Bool,
    'breakMaiden' : IDL.Bool,
    'runOut' : IDL.Bool,
    'totalRackScore' : IDL.Nat,
    'ballsOnBreakAwardedToOpponent' : IDL.Nat,
    'inningScore' : IDL.Int,
    'ballsOnBreak' : IDL.Int,
    'deadBalls' : IDL.Nat,
  });
  const ApaPlayerStats = IDL.Record({
    'ppi' : IDL.Float64,
    'defensiveShots' : IDL.Nat,
    'matchBehaviorPhase' : IDL.Text,
    'playerId' : IDL.Principal,
    'pointsNeeded' : IDL.Nat,
    'pointsWonConverted' : IDL.Nat,
    'totalScore' : IDL.Int,
    'innings' : IDL.Nat,
    'winPercentage' : IDL.Float64,
    'pointsEarnedRunningTotal' : IDL.Nat,
    'isPlayerOfMatch' : IDL.Bool,
    'skillLevel' : IDL.Nat,
    'racks' : IDL.Vec(RackScore),
  });
  const TeamStats = IDL.Record({
    'teamName' : IDL.Text,
    'teamAverageScore' : IDL.Float64,
    'score' : IDL.Record({ 'totalPoints' : IDL.Int }),
    'playtimes' : IDL.Vec(IDL.Float64),
    'matchesPlayed' : IDL.Nat,
    'teamId' : IDL.Text,
    'matchesWon' : IDL.Nat,
    'teamWinState' : IDL.Variant({
      'win' : IDL.Text,
      'loss' : IDL.Text,
      'teammatchInProgress' : IDL.Null,
      'forfeit' : IDL.Text,
    }),
    'teamPenaltyState' : IDL.Variant({
      'penalty' : IDL.Text,
      'pending' : IDL.Null,
      'none' : IDL.Null,
      'penaltyAwarded' : IDL.Text,
    }),
  });
  const ApaNineBallMatch = IDL.Record({
    'matchType' : IDL.Text,
    'base' : BaseMatchEntry,
    'winner' : IDL.Principal,
    'playerStats' : IDL.Vec(ApaPlayerStats),
    'teamStats' : IDL.Vec(TeamStats),
    'umpire' : IDL.Opt(IDL.Principal),
    'seasonType' : IDL.Text,
  });
  const MatchLogRecord = IDL.Variant({
    'straightShot' : StraightShotMatch,
    'acceptingGifts' : AcceptingGiftsMatch,
    'officialApaMatchLog' : OfficialApaMatchLog,
    'practice' : PracticeMatch,
    'apaNineBall' : ApaNineBallMatch,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearHistory' : IDL.Func([], [], []),
    'completeSession' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'computeAPASummary' : IDL.Func(
        [IDL.Text, IDL.Vec(BallState)],
        [APADetailedInnningSummary],
        [],
      ),
    'deleteMatch' : IDL.Func([IDL.Text], [], []),
    'getAllMatches' : IDL.Func([], [IDL.Vec(ApiMatch)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentObjectBallCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getInviteOnlyMode' : IDL.Func([], [IDL.Bool], ['query']),
    'getMatch' : IDL.Func([IDL.Text], [IDL.Opt(ApiMatch)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveMatch' : IDL.Func([IDL.Text, MatchLogRecord], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setCurrentObjectBallCount' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'setInviteOnlyMode' : IDL.Func([IDL.Bool], [], []),
    'updateMatch' : IDL.Func([IDL.Text, MatchLogRecord], [], []),
  });
};

export const init = ({ IDL }) => { return []; };