/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    id: Principal;
    name: string;
    skillLevel?: bigint;
}
export interface BallState {
    by: string;
    id: bigint;
    all: string;
    eoi: boolean;
    inn: bigint;
    pna: bigint;
    ballNumber: bigint;
    calledShot: boolean;
    runOut: string;
    difficulty: string;
    rack: bigint;
    gameId: string;
    isBreak: boolean;
    defensiveShot: boolean;
    positionPlay: string;
    intendedPocket: string;
    score: bigint;
    pocketed: string;
    finalBall: bigint;
    activePlayer: string;
    defense: boolean;
    points: bigint;
}
export interface ApaNineBallMatch {
    matchType: string;
    base: BaseMatchEntry;
    winner: Principal;
    playerStats: Array<ApaPlayerStats>;
    teamStats: Array<TeamStats>;
    umpire?: Principal;
    seasonType: string;
}
export type Time = bigint;
export interface APAMatchStatsUiRackStats {
    extraStats: string;
    description: string;
    summary: string;
    matchId: string;
    playerStats: Array<APA9MatchPlayerStatsUi | null>;
    rackStats: Array<RackStat>;
    timestamp: Time;
    rackNumber: bigint;
}
export interface APA9MatchPlayerStatsUi {
    id: string;
    ppi: number;
    rankIcon: string;
    matchType: string;
    breakMaidenCount: bigint;
    defensiveShots: bigint;
    pointsAwarded: bigint;
    matchBehaviorPhase: string;
    totalBallsScoredPerRack: Array<bigint>;
    breakRuns: Array<bigint>;
    runOutAttempts: bigint;
    inningScores: Array<bigint>;
    rank: string;
    rackCount: bigint;
    pointsNeeded: bigint;
    deadBallsPerRack: Array<bigint>;
    pointsWonConverted: bigint;
    level: Variant_all_playerMatch_teamMatch_detailRack;
    totalScore: bigint;
    summary: string;
    rackStats: APAMatchStatsUiRackStats;
    innings: bigint;
    timestamp: Time;
    validBreakCount: bigint;
    ballsOnBreakAwardedToOpponentCount: bigint;
    winPercentage: number;
    pointsEarnedRunningTotal: bigint;
    isPlayerOfMatch: boolean;
    comments: string;
    skillLevel: bigint;
    runOutCount: bigint;
    umpire: string;
    racksPlayed: bigint;
    seasonType: string;
    location: string;
    ballsOnBreak: Array<bigint>;
    points: bigint;
}
export interface TeamStats {
    teamName: string;
    teamAverageScore: number;
    score: {
        totalPoints: bigint;
    };
    playtimes: Array<number>;
    matchesPlayed: bigint;
    teamId: string;
    matchesWon: bigint;
    teamWinState: {
        __kind__: "win";
        win: string;
    } | {
        __kind__: "loss";
        loss: string;
    } | {
        __kind__: "teammatchInProgress";
        teammatchInProgress: null;
    } | {
        __kind__: "forfeit";
        forfeit: string;
    };
    teamPenaltyState: {
        __kind__: "penalty";
        penalty: string;
    } | {
        __kind__: "pending";
        pending: null;
    } | {
        __kind__: "none";
        none: null;
    } | {
        __kind__: "penaltyAwarded";
        penaltyAwarded: string;
    };
}
export interface OfficialAPAMatchLogData {
    defensiveShots: string;
    theirScore: string;
    myScore: string;
    playerTwoSkillLevel?: bigint;
    date: string;
    opponentName: string;
    playerOneSkillLevel?: bigint;
    notes: string;
    innings: string;
    didWin?: boolean;
}
export interface APAMatchStatsUiContainer {
    matchType: string;
    summary: APAMatchStatsUiSummary;
    players: Array<APA9MatchPlayerStatsUi | null>;
    seasonType: string;
}
export interface OfficialAPAMatchLog {
    defensiveShots: string;
    theirScore: string;
    myScore: string;
    owner: Principal;
    playerTwoSkillLevel?: bigint;
    date: string;
    opponentName: string;
    matchId: string;
    playerOneSkillLevel?: bigint;
    notes: string;
    innings: string;
    didWin?: boolean;
    dateTime: Time;
}
export interface AcceptingGiftsMatch {
    startingObjectBallCount: bigint;
    completionStatus: boolean;
    base: BaseMatchEntry;
    endingObjectBallCount: bigint;
    score: bigint;
    finalSetScorePlayer: bigint;
    rulesReference: string;
    totalAttempts: bigint;
    finalSetScoreGhost: bigint;
    setsCompleted: bigint;
}
export interface APADetailedInnningSummary {
    defensiveShots: bigint;
    player: string;
    deadBalls: bigint;
    points: bigint;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface RackStat {
    extraStats: string;
    description: string;
    summary: string;
    matchId: string;
    timestamp: Time;
    rackNumberCopy: bigint;
    rackNumber: bigint;
}
export type MatchLogRecord = {
    __kind__: "straightShot";
    straightShot: StraightShotMatch;
} | {
    __kind__: "acceptingGifts";
    acceptingGifts: AcceptingGiftsMatch;
} | {
    __kind__: "officialApaMatchLog";
    officialApaMatchLog: OfficialAPAMatchLog;
} | {
    __kind__: "practice";
    practice: PracticeMatch;
} | {
    __kind__: "apaNineBall";
    apaNineBall: ApaNineBallMatch;
};
export interface ApaPlayerStats {
    ppi: number;
    defensiveShots: bigint;
    matchBehaviorPhase: string;
    playerId: Principal;
    pointsNeeded: bigint;
    pointsWonConverted: bigint;
    totalScore: bigint;
    innings: bigint;
    winPercentage: number;
    pointsEarnedRunningTotal: bigint;
    isPlayerOfMatch: boolean;
    skillLevel: bigint;
    racks: Array<RackScore>;
}
export interface BaseMatchEntry {
    owner: Principal;
    mode: MatchMode;
    matchId: string;
    players: Array<Player>;
    notes?: string;
    dateTime: Time;
}
export interface RackScore {
    validBreak: boolean;
    breakMaiden: boolean;
    runOut: boolean;
    totalRackScore: bigint;
    ballsOnBreakAwardedToOpponent: bigint;
    inningScore: bigint;
    ballsOnBreak: bigint;
    deadBalls: bigint;
}
export interface StraightShotMatch {
    base: BaseMatchEntry;
    scratchStrokes: Array<bigint>;
    time?: bigint;
    score: {
        firstShot: bigint;
        total: bigint;
        fourthShot: bigint;
        thirdShot: bigint;
        secondShot: bigint;
    };
    shots: bigint;
    ballsMade: bigint;
    strokes: Array<bigint>;
}
export interface APAMatchStatsUiSummary {
    id: string;
    matchType: string;
    extraStats: string;
    pointsAwarded: bigint;
    level: Variant_all_playerMatch_teamMatch_detailRack;
    summary: string;
    playerStats: Array<APA9MatchPlayerStatsUi | null>;
    rackStats: APAMatchStatsUiRackStats;
    timestamp: Time;
    isInProgress: boolean;
    comments: string;
    phase: string;
    umpire?: Principal;
    seasonType: string;
    location: string;
    points: bigint;
}
export interface ApiMatch {
    makes?: bigint;
    thirdShotScore?: bigint;
    startingObjectBallCount?: bigint;
    completionTime?: bigint;
    completionStatus?: boolean;
    owner: Principal;
    scratchStrokes?: Array<bigint>;
    mode: MatchMode;
    attempts?: bigint;
    endingObjectBallCount?: bigint;
    score?: bigint;
    shots?: bigint;
    finalSetScorePlayer?: bigint;
    totalScore?: bigint;
    rulesReference?: string;
    fourthShotScore?: bigint;
    matchId: string;
    players: Array<Player>;
    totalAttempts?: bigint;
    firstShotScore?: bigint;
    ballsMade?: bigint;
    notes?: string;
    apaMatchInfo?: APAMatchStatsUiContainer;
    secondShotScore?: bigint;
    dateTime: Time;
    officialApaMatchLogData?: OfficialAPAMatchLogData;
    finalSetScoreGhost?: bigint;
    streaks?: bigint;
    strokes?: Array<bigint>;
    setsCompleted?: bigint;
}
export interface UserProfile {
    name: string;
    apaSkillLevel?: bigint;
}
export interface PracticeMatch {
    makes?: bigint;
    base: BaseMatchEntry;
    attempts?: bigint;
    streaks?: bigint;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum MatchMode {
    straightShot = "straightShot",
    apaPractice = "apaPractice",
    acceptingGifts = "acceptingGifts"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_all_playerMatch_teamMatch_detailRack {
    all = "all",
    playerMatch = "playerMatch",
    teamMatch = "teamMatch",
    detailRack = "detailRack"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearHistory(): Promise<void>;
    completeAgSession(finalLevel: bigint): Promise<bigint>;
    computeAPASummary(startingPlayer: string, ballStates: Array<BallState>): Promise<APADetailedInnningSummary>;
    deleteMatch(matchId: string): Promise<void>;
    deleteMatches(matchIds: Array<string>): Promise<void>;
    getAgLevelIndex(): Promise<bigint>;
    getAllMatches(): Promise<Array<ApiMatch>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getInviteOnlyMode(): Promise<boolean>;
    getMatch(matchId: string): Promise<ApiMatch | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveMatch(matchId: string, matchRecord: MatchLogRecord): Promise<void>;
    setAgLevelIndex(newLevel: bigint): Promise<bigint>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setInviteOnlyMode(enabled: boolean): Promise<void>;
    updateMatch(matchId: string, updatedMatch: MatchLogRecord): Promise<void>;
}
import type { APA9MatchPlayerStatsUi as _APA9MatchPlayerStatsUi, APAMatchStatsUiContainer as _APAMatchStatsUiContainer, APAMatchStatsUiRackStats as _APAMatchStatsUiRackStats, APAMatchStatsUiSummary as _APAMatchStatsUiSummary, AcceptingGiftsMatch as _AcceptingGiftsMatch, ApaNineBallMatch as _ApaNineBallMatch, ApaPlayerStats as _ApaPlayerStats, ApiMatch as _ApiMatch, ApprovalStatus as _ApprovalStatus, BaseMatchEntry as _BaseMatchEntry, MatchLogRecord as _MatchLogRecord, MatchMode as _MatchMode, OfficialAPAMatchLog as _OfficialAPAMatchLog, OfficialAPAMatchLogData as _OfficialAPAMatchLogData, Player as _Player, PracticeMatch as _PracticeMatch, RackStat as _RackStat, StraightShotMatch as _StraightShotMatch, TeamStats as _TeamStats, Time as _Time, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearHistory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearHistory();
            return result;
        }
    }
    async completeAgSession(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.completeAgSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeAgSession(arg0);
            return result;
        }
    }
    async computeAPASummary(arg0: string, arg1: Array<BallState>): Promise<APADetailedInnningSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.computeAPASummary(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.computeAPASummary(arg0, arg1);
            return result;
        }
    }
    async deleteMatch(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMatch(arg0);
            return result;
        }
    }
    async deleteMatches(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMatches(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMatches(arg0);
            return result;
        }
    }
    async getAgLevelIndex(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgLevelIndex();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgLevelIndex();
            return result;
        }
    }
    async getAllMatches(): Promise<Array<ApiMatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMatches();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMatches();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInviteOnlyMode(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteOnlyMode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteOnlyMode();
            return result;
        }
    }
    async getMatch(arg0: string): Promise<ApiMatch | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n42(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n42(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveMatch(arg0: string, arg1: MatchLogRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMatch(arg0, to_candid_MatchLogRecord_n44(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMatch(arg0, to_candid_MatchLogRecord_n44(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setAgLevelIndex(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.setAgLevelIndex(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAgLevelIndex(arg0);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n68(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n68(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setInviteOnlyMode(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setInviteOnlyMode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setInviteOnlyMode(arg0);
            return result;
        }
    }
    async updateMatch(arg0: string, arg1: MatchLogRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMatch(arg0, to_candid_MatchLogRecord_n44(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMatch(arg0, to_candid_MatchLogRecord_n44(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_APA9MatchPlayerStatsUi_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _APA9MatchPlayerStatsUi): APA9MatchPlayerStatsUi {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_APAMatchStatsUiContainer_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _APAMatchStatsUiContainer): APAMatchStatsUiContainer {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_APAMatchStatsUiRackStats_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _APAMatchStatsUiRackStats): APAMatchStatsUiRackStats {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_APAMatchStatsUiSummary_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _APAMatchStatsUiSummary): APAMatchStatsUiSummary {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ApiMatch_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiMatch): ApiMatch {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_MatchMode_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchMode): MatchMode {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_OfficialAPAMatchLogData_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OfficialAPAMatchLogData): OfficialAPAMatchLogData {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Player_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Player): Player {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_APAMatchStatsUiContainer]): APAMatchStatsUiContainer | null {
    return value.length === 0 ? null : from_candid_APAMatchStatsUiContainer_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_APA9MatchPlayerStatsUi]): APA9MatchPlayerStatsUi | null {
    return value.length === 0 ? null : from_candid_APA9MatchPlayerStatsUi_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OfficialAPAMatchLogData]): OfficialAPAMatchLogData | null {
    return value.length === 0 ? null : from_candid_OfficialAPAMatchLogData_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ApiMatch]): ApiMatch | null {
    return value.length === 0 ? null : from_candid_ApiMatch_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<bigint>]): Array<bigint> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    skillLevel: [] | [bigint];
}): {
    id: Principal;
    name: string;
    skillLevel?: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        skillLevel: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.skillLevel))
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    matchType: string;
    summary: _APAMatchStatsUiSummary;
    players: Array<[] | [_APA9MatchPlayerStatsUi]>;
    seasonType: string;
}): {
    matchType: string;
    summary: APAMatchStatsUiSummary;
    players: Array<APA9MatchPlayerStatsUi | null>;
    seasonType: string;
} {
    return {
        matchType: value.matchType,
        summary: from_candid_APAMatchStatsUiSummary_n18(_uploadFile, _downloadFile, value.summary),
        players: from_candid_vec_n21(_uploadFile, _downloadFile, value.players),
        seasonType: value.seasonType
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    matchType: string;
    extraStats: string;
    pointsAwarded: bigint;
    level: {
        all: null;
    } | {
        playerMatch: null;
    } | {
        teamMatch: null;
    } | {
        detailRack: null;
    };
    summary: string;
    playerStats: Array<[] | [_APA9MatchPlayerStatsUi]>;
    rackStats: _APAMatchStatsUiRackStats;
    timestamp: _Time;
    isInProgress: boolean;
    comments: string;
    phase: string;
    umpire: [] | [Principal];
    seasonType: string;
    location: string;
    points: bigint;
}): {
    id: string;
    matchType: string;
    extraStats: string;
    pointsAwarded: bigint;
    level: Variant_all_playerMatch_teamMatch_detailRack;
    summary: string;
    playerStats: Array<APA9MatchPlayerStatsUi | null>;
    rackStats: APAMatchStatsUiRackStats;
    timestamp: Time;
    isInProgress: boolean;
    comments: string;
    phase: string;
    umpire?: Principal;
    seasonType: string;
    location: string;
    points: bigint;
} {
    return {
        id: value.id,
        matchType: value.matchType,
        extraStats: value.extraStats,
        pointsAwarded: value.pointsAwarded,
        level: from_candid_variant_n20(_uploadFile, _downloadFile, value.level),
        summary: value.summary,
        playerStats: from_candid_vec_n21(_uploadFile, _downloadFile, value.playerStats),
        rackStats: from_candid_APAMatchStatsUiRackStats_n25(_uploadFile, _downloadFile, value.rackStats),
        timestamp: value.timestamp,
        isInProgress: value.isInProgress,
        comments: value.comments,
        phase: value.phase,
        umpire: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.umpire)),
        seasonType: value.seasonType,
        location: value.location,
        points: value.points
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    ppi: number;
    rankIcon: string;
    matchType: string;
    breakMaidenCount: bigint;
    defensiveShots: bigint;
    pointsAwarded: bigint;
    matchBehaviorPhase: string;
    totalBallsScoredPerRack: Array<bigint>;
    breakRuns: Array<bigint>;
    runOutAttempts: bigint;
    inningScores: Array<bigint>;
    rank: string;
    rackCount: bigint;
    pointsNeeded: bigint;
    deadBallsPerRack: Array<bigint>;
    pointsWonConverted: bigint;
    level: {
        all: null;
    } | {
        playerMatch: null;
    } | {
        teamMatch: null;
    } | {
        detailRack: null;
    };
    totalScore: bigint;
    summary: string;
    rackStats: _APAMatchStatsUiRackStats;
    innings: bigint;
    timestamp: _Time;
    validBreakCount: bigint;
    ballsOnBreakAwardedToOpponentCount: bigint;
    winPercentage: number;
    pointsEarnedRunningTotal: bigint;
    isPlayerOfMatch: boolean;
    comments: string;
    skillLevel: bigint;
    runOutCount: bigint;
    umpire: string;
    racksPlayed: bigint;
    seasonType: string;
    location: string;
    ballsOnBreak: Array<bigint>;
    points: bigint;
}): {
    id: string;
    ppi: number;
    rankIcon: string;
    matchType: string;
    breakMaidenCount: bigint;
    defensiveShots: bigint;
    pointsAwarded: bigint;
    matchBehaviorPhase: string;
    totalBallsScoredPerRack: Array<bigint>;
    breakRuns: Array<bigint>;
    runOutAttempts: bigint;
    inningScores: Array<bigint>;
    rank: string;
    rackCount: bigint;
    pointsNeeded: bigint;
    deadBallsPerRack: Array<bigint>;
    pointsWonConverted: bigint;
    level: Variant_all_playerMatch_teamMatch_detailRack;
    totalScore: bigint;
    summary: string;
    rackStats: APAMatchStatsUiRackStats;
    innings: bigint;
    timestamp: Time;
    validBreakCount: bigint;
    ballsOnBreakAwardedToOpponentCount: bigint;
    winPercentage: number;
    pointsEarnedRunningTotal: bigint;
    isPlayerOfMatch: boolean;
    comments: string;
    skillLevel: bigint;
    runOutCount: bigint;
    umpire: string;
    racksPlayed: bigint;
    seasonType: string;
    location: string;
    ballsOnBreak: Array<bigint>;
    points: bigint;
} {
    return {
        id: value.id,
        ppi: value.ppi,
        rankIcon: value.rankIcon,
        matchType: value.matchType,
        breakMaidenCount: value.breakMaidenCount,
        defensiveShots: value.defensiveShots,
        pointsAwarded: value.pointsAwarded,
        matchBehaviorPhase: value.matchBehaviorPhase,
        totalBallsScoredPerRack: value.totalBallsScoredPerRack,
        breakRuns: value.breakRuns,
        runOutAttempts: value.runOutAttempts,
        inningScores: value.inningScores,
        rank: value.rank,
        rackCount: value.rackCount,
        pointsNeeded: value.pointsNeeded,
        deadBallsPerRack: value.deadBallsPerRack,
        pointsWonConverted: value.pointsWonConverted,
        level: from_candid_variant_n20(_uploadFile, _downloadFile, value.level),
        totalScore: value.totalScore,
        summary: value.summary,
        rackStats: from_candid_APAMatchStatsUiRackStats_n25(_uploadFile, _downloadFile, value.rackStats),
        innings: value.innings,
        timestamp: value.timestamp,
        validBreakCount: value.validBreakCount,
        ballsOnBreakAwardedToOpponentCount: value.ballsOnBreakAwardedToOpponentCount,
        winPercentage: value.winPercentage,
        pointsEarnedRunningTotal: value.pointsEarnedRunningTotal,
        isPlayerOfMatch: value.isPlayerOfMatch,
        comments: value.comments,
        skillLevel: value.skillLevel,
        runOutCount: value.runOutCount,
        umpire: value.umpire,
        racksPlayed: value.racksPlayed,
        seasonType: value.seasonType,
        location: value.location,
        ballsOnBreak: value.ballsOnBreak,
        points: value.points
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    extraStats: string;
    description: string;
    summary: string;
    matchId: string;
    playerStats: Array<[] | [_APA9MatchPlayerStatsUi]>;
    rackStats: Array<_RackStat>;
    timestamp: _Time;
    rackNumber: bigint;
}): {
    extraStats: string;
    description: string;
    summary: string;
    matchId: string;
    playerStats: Array<APA9MatchPlayerStatsUi | null>;
    rackStats: Array<RackStat>;
    timestamp: Time;
    rackNumber: bigint;
} {
    return {
        extraStats: value.extraStats,
        description: value.description,
        summary: value.summary,
        matchId: value.matchId,
        playerStats: from_candid_vec_n21(_uploadFile, _downloadFile, value.playerStats),
        rackStats: value.rackStats,
        timestamp: value.timestamp,
        rackNumber: value.rackNumber
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    defensiveShots: string;
    theirScore: string;
    myScore: string;
    playerTwoSkillLevel: [] | [bigint];
    date: string;
    opponentName: string;
    playerOneSkillLevel: [] | [bigint];
    notes: string;
    innings: string;
    didWin: [] | [boolean];
}): {
    defensiveShots: string;
    theirScore: string;
    myScore: string;
    playerTwoSkillLevel?: bigint;
    date: string;
    opponentName: string;
    playerOneSkillLevel?: bigint;
    notes: string;
    innings: string;
    didWin?: boolean;
} {
    return {
        defensiveShots: value.defensiveShots,
        theirScore: value.theirScore,
        myScore: value.myScore,
        playerTwoSkillLevel: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.playerTwoSkillLevel)),
        date: value.date,
        opponentName: value.opponentName,
        playerOneSkillLevel: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.playerOneSkillLevel)),
        notes: value.notes,
        innings: value.innings,
        didWin: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.didWin))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    apaSkillLevel: [] | [bigint];
}): {
    name: string;
    apaSkillLevel?: bigint;
} {
    return {
        name: value.name,
        apaSkillLevel: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.apaSkillLevel))
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n40(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    makes: [] | [bigint];
    thirdShotScore: [] | [bigint];
    startingObjectBallCount: [] | [bigint];
    completionTime: [] | [bigint];
    completionStatus: [] | [boolean];
    owner: Principal;
    scratchStrokes: [] | [Array<bigint>];
    mode: _MatchMode;
    attempts: [] | [bigint];
    endingObjectBallCount: [] | [bigint];
    score: [] | [bigint];
    shots: [] | [bigint];
    finalSetScorePlayer: [] | [bigint];
    totalScore: [] | [bigint];
    rulesReference: [] | [string];
    fourthShotScore: [] | [bigint];
    matchId: string;
    players: Array<_Player>;
    totalAttempts: [] | [bigint];
    firstShotScore: [] | [bigint];
    ballsMade: [] | [bigint];
    notes: [] | [string];
    apaMatchInfo: [] | [_APAMatchStatsUiContainer];
    secondShotScore: [] | [bigint];
    dateTime: _Time;
    officialApaMatchLogData: [] | [_OfficialAPAMatchLogData];
    finalSetScoreGhost: [] | [bigint];
    streaks: [] | [bigint];
    strokes: [] | [Array<bigint>];
    setsCompleted: [] | [bigint];
}): {
    makes?: bigint;
    thirdShotScore?: bigint;
    startingObjectBallCount?: bigint;
    completionTime?: bigint;
    completionStatus?: boolean;
    owner: Principal;
    scratchStrokes?: Array<bigint>;
    mode: MatchMode;
    attempts?: bigint;
    endingObjectBallCount?: bigint;
    score?: bigint;
    shots?: bigint;
    finalSetScorePlayer?: bigint;
    totalScore?: bigint;
    rulesReference?: string;
    fourthShotScore?: bigint;
    matchId: string;
    players: Array<Player>;
    totalAttempts?: bigint;
    firstShotScore?: bigint;
    ballsMade?: bigint;
    notes?: string;
    apaMatchInfo?: APAMatchStatsUiContainer;
    secondShotScore?: bigint;
    dateTime: Time;
    officialApaMatchLogData?: OfficialAPAMatchLogData;
    finalSetScoreGhost?: bigint;
    streaks?: bigint;
    strokes?: Array<bigint>;
    setsCompleted?: bigint;
} {
    return {
        makes: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.makes)),
        thirdShotScore: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.thirdShotScore)),
        startingObjectBallCount: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.startingObjectBallCount)),
        completionTime: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.completionTime)),
        completionStatus: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.completionStatus)),
        owner: value.owner,
        scratchStrokes: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.scratchStrokes)),
        mode: from_candid_MatchMode_n9(_uploadFile, _downloadFile, value.mode),
        attempts: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.attempts)),
        endingObjectBallCount: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.endingObjectBallCount)),
        score: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.score)),
        shots: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.shots)),
        finalSetScorePlayer: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.finalSetScorePlayer)),
        totalScore: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.totalScore)),
        rulesReference: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.rulesReference)),
        fourthShotScore: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.fourthShotScore)),
        matchId: value.matchId,
        players: from_candid_vec_n12(_uploadFile, _downloadFile, value.players),
        totalAttempts: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.totalAttempts)),
        firstShotScore: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.firstShotScore)),
        ballsMade: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.ballsMade)),
        notes: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.notes)),
        apaMatchInfo: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.apaMatchInfo)),
        secondShotScore: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.secondShotScore)),
        dateTime: value.dateTime,
        officialApaMatchLogData: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.officialApaMatchLogData)),
        finalSetScoreGhost: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.finalSetScoreGhost)),
        streaks: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.streaks)),
        strokes: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.strokes)),
        setsCompleted: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.setsCompleted))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    straightShot: null;
} | {
    apaPractice: null;
} | {
    acceptingGifts: null;
}): MatchMode {
    return "straightShot" in value ? MatchMode.straightShot : "apaPractice" in value ? MatchMode.apaPractice : "acceptingGifts" in value ? MatchMode.acceptingGifts : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    all: null;
} | {
    playerMatch: null;
} | {
    teamMatch: null;
} | {
    detailRack: null;
}): Variant_all_playerMatch_teamMatch_detailRack {
    return "all" in value ? Variant_all_playerMatch_teamMatch_detailRack.all : "playerMatch" in value ? Variant_all_playerMatch_teamMatch_detailRack.playerMatch : "teamMatch" in value ? Variant_all_playerMatch_teamMatch_detailRack.teamMatch : "detailRack" in value ? Variant_all_playerMatch_teamMatch_detailRack.detailRack : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Player>): Array<Player> {
    return value.map((x)=>from_candid_Player_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[] | [_APA9MatchPlayerStatsUi]>): Array<APA9MatchPlayerStatsUi | null> {
    return value.map((x)=>from_candid_opt_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApiMatch>): Array<ApiMatch> {
    return value.map((x)=>from_candid_ApiMatch_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n38(_uploadFile, _downloadFile, x));
}
function to_candid_AcceptingGiftsMatch_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AcceptingGiftsMatch): _AcceptingGiftsMatch {
    return to_candid_record_n65(_uploadFile, _downloadFile, value);
}
function to_candid_ApaNineBallMatch_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApaNineBallMatch): _ApaNineBallMatch {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_ApprovalStatus_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function to_candid_BaseMatchEntry_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BaseMatchEntry): _BaseMatchEntry {
    return to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_MatchLogRecord_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchLogRecord): _MatchLogRecord {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_MatchMode_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchMode): _MatchMode {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_OfficialAPAMatchLog_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OfficialAPAMatchLog): _OfficialAPAMatchLog {
    return to_candid_record_n63(_uploadFile, _downloadFile, value);
}
function to_candid_Player_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Player): _Player {
    return to_candid_record_n54(_uploadFile, _downloadFile, value);
}
function to_candid_PracticeMatch_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PracticeMatch): _PracticeMatch {
    return to_candid_record_n61(_uploadFile, _downloadFile, value);
}
function to_candid_StraightShotMatch_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StraightShotMatch): _StraightShotMatch {
    return to_candid_record_n67(_uploadFile, _downloadFile, value);
}
function to_candid_TeamStats_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeamStats): _TeamStats {
    return to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    apaSkillLevel?: bigint;
}): {
    name: string;
    apaSkillLevel: [] | [bigint];
} {
    return {
        name: value.name,
        apaSkillLevel: value.apaSkillLevel ? candid_some(value.apaSkillLevel) : candid_none()
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    matchType: string;
    base: BaseMatchEntry;
    winner: Principal;
    playerStats: Array<ApaPlayerStats>;
    teamStats: Array<TeamStats>;
    umpire?: Principal;
    seasonType: string;
}): {
    matchType: string;
    base: _BaseMatchEntry;
    winner: Principal;
    playerStats: Array<_ApaPlayerStats>;
    teamStats: Array<_TeamStats>;
    umpire: [] | [Principal];
    seasonType: string;
} {
    return {
        matchType: value.matchType,
        base: to_candid_BaseMatchEntry_n48(_uploadFile, _downloadFile, value.base),
        winner: value.winner,
        playerStats: value.playerStats,
        teamStats: to_candid_vec_n55(_uploadFile, _downloadFile, value.teamStats),
        umpire: value.umpire ? candid_some(value.umpire) : candid_none(),
        seasonType: value.seasonType
    };
}
function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: Principal;
    mode: MatchMode;
    matchId: string;
    players: Array<Player>;
    notes?: string;
    dateTime: Time;
}): {
    owner: Principal;
    mode: _MatchMode;
    matchId: string;
    players: Array<_Player>;
    notes: [] | [string];
    dateTime: _Time;
} {
    return {
        owner: value.owner,
        mode: to_candid_MatchMode_n50(_uploadFile, _downloadFile, value.mode),
        matchId: value.matchId,
        players: to_candid_vec_n52(_uploadFile, _downloadFile, value.players),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        dateTime: value.dateTime
    };
}
function to_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    skillLevel?: bigint;
}): {
    id: Principal;
    name: string;
    skillLevel: [] | [bigint];
} {
    return {
        id: value.id,
        name: value.name,
        skillLevel: value.skillLevel ? candid_some(value.skillLevel) : candid_none()
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    teamName: string;
    teamAverageScore: number;
    score: {
        totalPoints: bigint;
    };
    playtimes: Array<number>;
    matchesPlayed: bigint;
    teamId: string;
    matchesWon: bigint;
    teamWinState: {
        __kind__: "win";
        win: string;
    } | {
        __kind__: "loss";
        loss: string;
    } | {
        __kind__: "teammatchInProgress";
        teammatchInProgress: null;
    } | {
        __kind__: "forfeit";
        forfeit: string;
    };
    teamPenaltyState: {
        __kind__: "penalty";
        penalty: string;
    } | {
        __kind__: "pending";
        pending: null;
    } | {
        __kind__: "none";
        none: null;
    } | {
        __kind__: "penaltyAwarded";
        penaltyAwarded: string;
    };
}): {
    teamName: string;
    teamAverageScore: number;
    score: {
        totalPoints: bigint;
    };
    playtimes: Array<number>;
    matchesPlayed: bigint;
    teamId: string;
    matchesWon: bigint;
    teamWinState: {
        win: string;
    } | {
        loss: string;
    } | {
        teammatchInProgress: null;
    } | {
        forfeit: string;
    };
    teamPenaltyState: {
        penalty: string;
    } | {
        pending: null;
    } | {
        none: null;
    } | {
        penaltyAwarded: string;
    };
} {
    return {
        teamName: value.teamName,
        teamAverageScore: value.teamAverageScore,
        score: value.score,
        playtimes: value.playtimes,
        matchesPlayed: value.matchesPlayed,
        teamId: value.teamId,
        matchesWon: value.matchesWon,
        teamWinState: to_candid_variant_n58(_uploadFile, _downloadFile, value.teamWinState),
        teamPenaltyState: to_candid_variant_n59(_uploadFile, _downloadFile, value.teamPenaltyState)
    };
}
function to_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    makes?: bigint;
    base: BaseMatchEntry;
    attempts?: bigint;
    streaks?: bigint;
}): {
    makes: [] | [bigint];
    base: _BaseMatchEntry;
    attempts: [] | [bigint];
    streaks: [] | [bigint];
} {
    return {
        makes: value.makes ? candid_some(value.makes) : candid_none(),
        base: to_candid_BaseMatchEntry_n48(_uploadFile, _downloadFile, value.base),
        attempts: value.attempts ? candid_some(value.attempts) : candid_none(),
        streaks: value.streaks ? candid_some(value.streaks) : candid_none()
    };
}
function to_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    defensiveShots: string;
    theirScore: string;
    myScore: string;
    owner: Principal;
    playerTwoSkillLevel?: bigint;
    date: string;
    opponentName: string;
    matchId: string;
    playerOneSkillLevel?: bigint;
    notes: string;
    innings: string;
    didWin?: boolean;
    dateTime: Time;
}): {
    defensiveShots: string;
    theirScore: string;
    myScore: string;
    owner: Principal;
    playerTwoSkillLevel: [] | [bigint];
    date: string;
    opponentName: string;
    matchId: string;
    playerOneSkillLevel: [] | [bigint];
    notes: string;
    innings: string;
    didWin: [] | [boolean];
    dateTime: _Time;
} {
    return {
        defensiveShots: value.defensiveShots,
        theirScore: value.theirScore,
        myScore: value.myScore,
        owner: value.owner,
        playerTwoSkillLevel: value.playerTwoSkillLevel ? candid_some(value.playerTwoSkillLevel) : candid_none(),
        date: value.date,
        opponentName: value.opponentName,
        matchId: value.matchId,
        playerOneSkillLevel: value.playerOneSkillLevel ? candid_some(value.playerOneSkillLevel) : candid_none(),
        notes: value.notes,
        innings: value.innings,
        didWin: value.didWin ? candid_some(value.didWin) : candid_none(),
        dateTime: value.dateTime
    };
}
function to_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startingObjectBallCount: bigint;
    completionStatus: boolean;
    base: BaseMatchEntry;
    endingObjectBallCount: bigint;
    score: bigint;
    finalSetScorePlayer: bigint;
    rulesReference: string;
    totalAttempts: bigint;
    finalSetScoreGhost: bigint;
    setsCompleted: bigint;
}): {
    startingObjectBallCount: bigint;
    completionStatus: boolean;
    base: _BaseMatchEntry;
    endingObjectBallCount: bigint;
    score: bigint;
    finalSetScorePlayer: bigint;
    rulesReference: string;
    totalAttempts: bigint;
    finalSetScoreGhost: bigint;
    setsCompleted: bigint;
} {
    return {
        startingObjectBallCount: value.startingObjectBallCount,
        completionStatus: value.completionStatus,
        base: to_candid_BaseMatchEntry_n48(_uploadFile, _downloadFile, value.base),
        endingObjectBallCount: value.endingObjectBallCount,
        score: value.score,
        finalSetScorePlayer: value.finalSetScorePlayer,
        rulesReference: value.rulesReference,
        totalAttempts: value.totalAttempts,
        finalSetScoreGhost: value.finalSetScoreGhost,
        setsCompleted: value.setsCompleted
    };
}
function to_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    base: BaseMatchEntry;
    scratchStrokes: Array<bigint>;
    time?: bigint;
    score: {
        firstShot: bigint;
        total: bigint;
        fourthShot: bigint;
        thirdShot: bigint;
        secondShot: bigint;
    };
    shots: bigint;
    ballsMade: bigint;
    strokes: Array<bigint>;
}): {
    base: _BaseMatchEntry;
    scratchStrokes: Array<bigint>;
    time: [] | [bigint];
    score: {
        firstShot: bigint;
        total: bigint;
        fourthShot: bigint;
        thirdShot: bigint;
        secondShot: bigint;
    };
    shots: bigint;
    ballsMade: bigint;
    strokes: Array<bigint>;
} {
    return {
        base: to_candid_BaseMatchEntry_n48(_uploadFile, _downloadFile, value.base),
        scratchStrokes: value.scratchStrokes,
        time: value.time ? candid_some(value.time) : candid_none(),
        score: value.score,
        shots: value.shots,
        ballsMade: value.ballsMade,
        strokes: value.strokes
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "straightShot";
    straightShot: StraightShotMatch;
} | {
    __kind__: "acceptingGifts";
    acceptingGifts: AcceptingGiftsMatch;
} | {
    __kind__: "officialApaMatchLog";
    officialApaMatchLog: OfficialAPAMatchLog;
} | {
    __kind__: "practice";
    practice: PracticeMatch;
} | {
    __kind__: "apaNineBall";
    apaNineBall: ApaNineBallMatch;
}): {
    straightShot: _StraightShotMatch;
} | {
    acceptingGifts: _AcceptingGiftsMatch;
} | {
    officialApaMatchLog: _OfficialAPAMatchLog;
} | {
    practice: _PracticeMatch;
} | {
    apaNineBall: _ApaNineBallMatch;
} {
    return value.__kind__ === "straightShot" ? {
        straightShot: to_candid_StraightShotMatch_n66(_uploadFile, _downloadFile, value.straightShot)
    } : value.__kind__ === "acceptingGifts" ? {
        acceptingGifts: to_candid_AcceptingGiftsMatch_n64(_uploadFile, _downloadFile, value.acceptingGifts)
    } : value.__kind__ === "officialApaMatchLog" ? {
        officialApaMatchLog: to_candid_OfficialAPAMatchLog_n62(_uploadFile, _downloadFile, value.officialApaMatchLog)
    } : value.__kind__ === "practice" ? {
        practice: to_candid_PracticeMatch_n60(_uploadFile, _downloadFile, value.practice)
    } : value.__kind__ === "apaNineBall" ? {
        apaNineBall: to_candid_ApaNineBallMatch_n46(_uploadFile, _downloadFile, value.apaNineBall)
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchMode): {
    straightShot: null;
} | {
    apaPractice: null;
} | {
    acceptingGifts: null;
} {
    return value == MatchMode.straightShot ? {
        straightShot: null
    } : value == MatchMode.apaPractice ? {
        apaPractice: null
    } : value == MatchMode.acceptingGifts ? {
        acceptingGifts: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "win";
    win: string;
} | {
    __kind__: "loss";
    loss: string;
} | {
    __kind__: "teammatchInProgress";
    teammatchInProgress: null;
} | {
    __kind__: "forfeit";
    forfeit: string;
}): {
    win: string;
} | {
    loss: string;
} | {
    teammatchInProgress: null;
} | {
    forfeit: string;
} {
    return value.__kind__ === "win" ? {
        win: value.win
    } : value.__kind__ === "loss" ? {
        loss: value.loss
    } : value.__kind__ === "teammatchInProgress" ? {
        teammatchInProgress: value.teammatchInProgress
    } : value.__kind__ === "forfeit" ? {
        forfeit: value.forfeit
    } : value;
}
function to_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "penalty";
    penalty: string;
} | {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "none";
    none: null;
} | {
    __kind__: "penaltyAwarded";
    penaltyAwarded: string;
}): {
    penalty: string;
} | {
    pending: null;
} | {
    none: null;
} | {
    penaltyAwarded: string;
} {
    return value.__kind__ === "penalty" ? {
        penalty: value.penalty
    } : value.__kind__ === "pending" ? {
        pending: value.pending
    } : value.__kind__ === "none" ? {
        none: value.none
    } : value.__kind__ === "penaltyAwarded" ? {
        penaltyAwarded: value.penaltyAwarded
    } : value;
}
function to_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Player>): Array<_Player> {
    return value.map((x)=>to_candid_Player_n53(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TeamStats>): Array<_TeamStats> {
    return value.map((x)=>to_candid_TeamStats_n56(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
