/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    id: Principal;
    name: string;
    skillLevel?: bigint;
}
export interface AcceptingGiftsMatch {
    completionStatus: boolean;
    base: BaseMatchEntry;
    score: bigint;
    rulesReference: string;
}
export type Time = bigint;
export interface BaseMatchEntry {
    owner: Principal;
    mode: MatchMode;
    matchId: string;
    players: Array<Player>;
    notes?: string;
    dateTime: Time;
}
export interface StraightShotMatch {
    makes: bigint;
    completionTime?: bigint;
    base: BaseMatchEntry;
    attempts: bigint;
}
export type MatchRecord = {
    __kind__: "straightShot";
    straightShot: StraightShotMatch;
} | {
    __kind__: "acceptingGifts";
    acceptingGifts: AcceptingGiftsMatch;
} | {
    __kind__: "practice";
    practice: PracticeMatch;
};
export interface ApiMatch {
    makes?: bigint;
    completionTime?: bigint;
    completionStatus?: boolean;
    owner: Principal;
    mode: MatchMode;
    attempts?: bigint;
    score?: bigint;
    rulesReference?: string;
    matchId: string;
    players: Array<Player>;
    notes?: string;
    dateTime: Time;
    streaks?: bigint;
}
export interface UserProfile {
    name: string;
}
export interface PracticeMatch {
    makes?: bigint;
    base: BaseMatchEntry;
    attempts?: bigint;
    streaks?: bigint;
}
export enum MatchMode {
    straightShot = "straightShot",
    apaPractice = "apaPractice",
    acceptingGifts = "acceptingGifts"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearHistory(): Promise<void>;
    deleteMatch(matchId: string): Promise<void>;
    getAllMatches(): Promise<Array<ApiMatch>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMatch(matchId: string): Promise<ApiMatch | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveMatch(matchId: string, matchRecord: MatchRecord): Promise<void>;
    updateMatch(matchId: string, updatedMatch: MatchRecord): Promise<void>;
}
import type { AcceptingGiftsMatch as _AcceptingGiftsMatch, ApiMatch as _ApiMatch, BaseMatchEntry as _BaseMatchEntry, MatchMode as _MatchMode, MatchRecord as _MatchRecord, Player as _Player, PracticeMatch as _PracticeMatch, StraightShotMatch as _StraightShotMatch, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearHistory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearHistory();
            return result;
        }
    }
    async deleteMatch(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMatch(arg0);
            return result;
        }
    }
    async getAllMatches(): Promise<Array<ApiMatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMatches();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMatches();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatch(arg0: string): Promise<ApiMatch | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveMatch(arg0: string, arg1: MatchRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMatch(arg0, to_candid_MatchRecord_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMatch(arg0, to_candid_MatchRecord_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMatch(arg0: string, arg1: MatchRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMatch(arg0, to_candid_MatchRecord_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMatch(arg0, to_candid_MatchRecord_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ApiMatch_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiMatch): ApiMatch {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_MatchMode_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchMode): MatchMode {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Player_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Player): Player {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ApiMatch]): ApiMatch | null {
    return value.length === 0 ? null : from_candid_ApiMatch_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    skillLevel: [] | [bigint];
}): {
    id: Principal;
    name: string;
    skillLevel?: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        skillLevel: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.skillLevel))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    makes: [] | [bigint];
    completionTime: [] | [bigint];
    completionStatus: [] | [boolean];
    owner: Principal;
    mode: _MatchMode;
    attempts: [] | [bigint];
    score: [] | [bigint];
    rulesReference: [] | [string];
    matchId: string;
    players: Array<_Player>;
    notes: [] | [string];
    dateTime: _Time;
    streaks: [] | [bigint];
}): {
    makes?: bigint;
    completionTime?: bigint;
    completionStatus?: boolean;
    owner: Principal;
    mode: MatchMode;
    attempts?: bigint;
    score?: bigint;
    rulesReference?: string;
    matchId: string;
    players: Array<Player>;
    notes?: string;
    dateTime: Time;
    streaks?: bigint;
} {
    return {
        makes: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.makes)),
        completionTime: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.completionTime)),
        completionStatus: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.completionStatus)),
        owner: value.owner,
        mode: from_candid_MatchMode_n8(_uploadFile, _downloadFile, value.mode),
        attempts: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.attempts)),
        score: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.score)),
        rulesReference: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.rulesReference)),
        matchId: value.matchId,
        players: from_candid_vec_n11(_uploadFile, _downloadFile, value.players),
        notes: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.notes)),
        dateTime: value.dateTime,
        streaks: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.streaks))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    straightShot: null;
} | {
    apaPractice: null;
} | {
    acceptingGifts: null;
}): MatchMode {
    return "straightShot" in value ? MatchMode.straightShot : "apaPractice" in value ? MatchMode.apaPractice : "acceptingGifts" in value ? MatchMode.acceptingGifts : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Player>): Array<Player> {
    return value.map((x)=>from_candid_Player_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApiMatch>): Array<ApiMatch> {
    return value.map((x)=>from_candid_ApiMatch_n4(_uploadFile, _downloadFile, x));
}
function to_candid_AcceptingGiftsMatch_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AcceptingGiftsMatch): _AcceptingGiftsMatch {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_BaseMatchEntry_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BaseMatchEntry): _BaseMatchEntry {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_MatchMode_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchMode): _MatchMode {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_MatchRecord_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchRecord): _MatchRecord {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_Player_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Player): _Player {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_PracticeMatch_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PracticeMatch): _PracticeMatch {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_StraightShotMatch_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StraightShotMatch): _StraightShotMatch {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    makes?: bigint;
    base: BaseMatchEntry;
    attempts?: bigint;
    streaks?: bigint;
}): {
    makes: [] | [bigint];
    base: _BaseMatchEntry;
    attempts: [] | [bigint];
    streaks: [] | [bigint];
} {
    return {
        makes: value.makes ? candid_some(value.makes) : candid_none(),
        base: to_candid_BaseMatchEntry_n22(_uploadFile, _downloadFile, value.base),
        attempts: value.attempts ? candid_some(value.attempts) : candid_none(),
        streaks: value.streaks ? candid_some(value.streaks) : candid_none()
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: Principal;
    mode: MatchMode;
    matchId: string;
    players: Array<Player>;
    notes?: string;
    dateTime: Time;
}): {
    owner: Principal;
    mode: _MatchMode;
    matchId: string;
    players: Array<_Player>;
    notes: [] | [string];
    dateTime: _Time;
} {
    return {
        owner: value.owner,
        mode: to_candid_MatchMode_n24(_uploadFile, _downloadFile, value.mode),
        matchId: value.matchId,
        players: to_candid_vec_n26(_uploadFile, _downloadFile, value.players),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        dateTime: value.dateTime
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    skillLevel?: bigint;
}): {
    id: Principal;
    name: string;
    skillLevel: [] | [bigint];
} {
    return {
        id: value.id,
        name: value.name,
        skillLevel: value.skillLevel ? candid_some(value.skillLevel) : candid_none()
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completionStatus: boolean;
    base: BaseMatchEntry;
    score: bigint;
    rulesReference: string;
}): {
    completionStatus: boolean;
    base: _BaseMatchEntry;
    score: bigint;
    rulesReference: string;
} {
    return {
        completionStatus: value.completionStatus,
        base: to_candid_BaseMatchEntry_n22(_uploadFile, _downloadFile, value.base),
        score: value.score,
        rulesReference: value.rulesReference
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    makes: bigint;
    completionTime?: bigint;
    base: BaseMatchEntry;
    attempts: bigint;
}): {
    makes: bigint;
    completionTime: [] | [bigint];
    base: _BaseMatchEntry;
    attempts: bigint;
} {
    return {
        makes: value.makes,
        completionTime: value.completionTime ? candid_some(value.completionTime) : candid_none(),
        base: to_candid_BaseMatchEntry_n22(_uploadFile, _downloadFile, value.base),
        attempts: value.attempts
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "straightShot";
    straightShot: StraightShotMatch;
} | {
    __kind__: "acceptingGifts";
    acceptingGifts: AcceptingGiftsMatch;
} | {
    __kind__: "practice";
    practice: PracticeMatch;
}): {
    straightShot: _StraightShotMatch;
} | {
    acceptingGifts: _AcceptingGiftsMatch;
} | {
    practice: _PracticeMatch;
} {
    return value.__kind__ === "straightShot" ? {
        straightShot: to_candid_StraightShotMatch_n31(_uploadFile, _downloadFile, value.straightShot)
    } : value.__kind__ === "acceptingGifts" ? {
        acceptingGifts: to_candid_AcceptingGiftsMatch_n29(_uploadFile, _downloadFile, value.acceptingGifts)
    } : value.__kind__ === "practice" ? {
        practice: to_candid_PracticeMatch_n20(_uploadFile, _downloadFile, value.practice)
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchMode): {
    straightShot: null;
} | {
    apaPractice: null;
} | {
    acceptingGifts: null;
} {
    return value == MatchMode.straightShot ? {
        straightShot: null
    } : value == MatchMode.apaPractice ? {
        apaPractice: null
    } : value == MatchMode.acceptingGifts ? {
        acceptingGifts: null
    } : value;
}
function to_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Player>): Array<_Player> {
    return value.map((x)=>to_candid_Player_n27(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
